//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Forms.Layout {
    
    
    #region Component Designer generated code 
    public partial class ArrangedElementCollection_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::System.Windows.Forms.Layout.@__ArrangedElementCollection.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::System.Windows.Forms.Layout.ArrangedElementCollection), typeof(global::System.Windows.Forms.Layout.ArrangedElementCollection_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::System.Windows.Forms.Layout.ArrangedElementCollection), typeof(global::System.Windows.Forms.Layout.ArrangedElementCollection_))]
    internal sealed partial class @__ArrangedElementCollection : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__ArrangedElementCollection(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::System.Windows.Forms.Layout.@__ArrangedElementCollection.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__ArrangedElementCollection);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetEnumerator", "GetEnumerator0", "()Lsystem/collections/IEnumerator;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "CopyTo", "CopyTo1", "(Lsystem/Array;I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getCount", "Count2", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getSyncRoot", "SyncRoot3", "()Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "isSynchronized", "IsSynchronized4", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getItem", "Item5", "(I)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setItem", "Item6", "(ILsystem/Object;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Add", "Add7", "(Lsystem/Object;)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Contains", "Contains8", "(Lsystem/Object;)Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Clear", "Clear9", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "isReadOnly", "IsReadOnly10", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "isFixedSize", "IsFixedSize11", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "IndexOf", "IndexOf12", "(Lsystem/Object;)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Insert", "Insert13", "(ILsystem/Object;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Remove", "Remove14", "(Lsystem/Object;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RemoveAt", "RemoveAt15", "(I)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetEnumerator0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/collections/IEnumerator;
            // ()LSystem/Collections/IEnumerator;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.Layout.ArrangedElementCollection @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Layout.ArrangedElementCollection>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::System.Collections.IEnumerator>(@__env, ((global::System.Collections.IEnumerable)(@__real)).GetEnumerator());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void CopyTo1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle array, int index) {
            // (Lsystem/Array;I)V
            // (LSystem/Array;I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.Layout.ArrangedElementCollection @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Layout.ArrangedElementCollection>(@__env, @__obj);
            ((global::System.Collections.ICollection)(@__real)).CopyTo(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Array>(@__env, array), index);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static int Count2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Windows.Forms.Layout.ArrangedElementCollection @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Layout.ArrangedElementCollection>(@__env, @__obj);
            @__return = ((int)(((global::System.Collections.ICollection)(@__real)).Count));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle SyncRoot3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/Object;
            // ()LSystem/Object;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.Layout.ArrangedElementCollection @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Layout.ArrangedElementCollection>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<object>(@__env, ((global::System.Collections.ICollection)(@__real)).SyncRoot);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool IsSynchronized4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.Windows.Forms.Layout.ArrangedElementCollection @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Layout.ArrangedElementCollection>(@__env, @__obj);
            @__return = ((bool)(((global::System.Collections.ICollection)(@__real)).IsSynchronized));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Item5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index) {
            // (I)Lsystem/Object;
            // (I)LSystem/Object;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.Layout.ArrangedElementCollection @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Layout.ArrangedElementCollection>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<object>(@__env, ((global::System.Collections.IList)(@__real))[index]);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Item6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (ILsystem/Object;)V
            // (ILSystem/Object;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.Layout.ArrangedElementCollection @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Layout.ArrangedElementCollection>(@__env, @__obj);
            ((global::System.Collections.IList)(@__real))[index] = global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static int Add7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Object;)I
            // (LSystem/Object;)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Windows.Forms.Layout.ArrangedElementCollection @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Layout.ArrangedElementCollection>(@__env, @__obj);
            @__return = ((int)(((global::System.Collections.IList)(@__real)).Add(global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool Contains8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Object;)Z
            // (LSystem/Object;)Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.Windows.Forms.Layout.ArrangedElementCollection @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Layout.ArrangedElementCollection>(@__env, @__obj);
            @__return = ((bool)(((global::System.Collections.IList)(@__real)).Contains(global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Clear9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.Layout.ArrangedElementCollection @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Layout.ArrangedElementCollection>(@__env, @__obj);
            ((global::System.Collections.IList)(@__real)).Clear();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static bool IsReadOnly10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.Windows.Forms.Layout.ArrangedElementCollection @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Layout.ArrangedElementCollection>(@__env, @__obj);
            @__return = ((bool)(((global::System.Collections.IList)(@__real)).IsReadOnly));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool IsFixedSize11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.Windows.Forms.Layout.ArrangedElementCollection @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Layout.ArrangedElementCollection>(@__env, @__obj);
            @__return = ((bool)(((global::System.Collections.IList)(@__real)).IsFixedSize));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int IndexOf12(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Object;)I
            // (LSystem/Object;)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Windows.Forms.Layout.ArrangedElementCollection @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Layout.ArrangedElementCollection>(@__env, @__obj);
            @__return = ((int)(((global::System.Collections.IList)(@__real)).IndexOf(global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Insert13(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (ILsystem/Object;)V
            // (ILSystem/Object;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.Layout.ArrangedElementCollection @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Layout.ArrangedElementCollection>(@__env, @__obj);
            ((global::System.Collections.IList)(@__real)).Insert(index, global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Remove14(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Object;)V
            // (LSystem/Object;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.Layout.ArrangedElementCollection @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Layout.ArrangedElementCollection>(@__env, @__obj);
            ((global::System.Collections.IList)(@__real)).Remove(global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void RemoveAt15(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index) {
            // (I)V
            // (I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.Layout.ArrangedElementCollection @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Layout.ArrangedElementCollection>(@__env, @__obj);
            ((global::System.Collections.IList)(@__real)).RemoveAt(index);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::System.Windows.Forms.Layout.@__ArrangedElementCollection(@__env);
            }
        }
    }
    #endregion
}
