// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package scriptcs.embedded;

@net.sf.jni4net.attributes.ClrType
public class ExecutionManager extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected ExecutionManager(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected ExecutionManager() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native static void DestroyRuntime();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native static void InitRuntime();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/Object;")
    public native static system.Object ExecuteFile(java.lang.String file);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/Object;")
    public native static system.Object ExecuteText(java.lang.String text);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Exception;)LSystem/String;")
    public native static java.lang.String GetExceptionDetails(system.Exception exception);
    
    public static system.Type typeof() {
        return scriptcs.embedded.ExecutionManager.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        scriptcs.embedded.ExecutionManager.staticType = staticType;
    }
    //</generated-proxy>
}
