// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system.componentmodel;

@net.sf.jni4net.attributes.ClrType
public class Component extends system.MarshalByRefObject implements system.IDisposable {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Component(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public Component() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        system.componentmodel.Component.__ctorComponent0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorComponent0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void Dispose();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/ComponentModel/ISite;")
    public native system.Object getSite();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ISite;)V")
    public native void setSite(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addDisposed(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeDisposed(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/ComponentModel/IContainer;")
    public native system.IDisposable getContainer();
    
    public static system.Type typeof() {
        return system.componentmodel.Component.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        system.componentmodel.Component.staticType = staticType;
    }
    //</generated-proxy>
}
