//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace j4n {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class A : global::java.lang.Object, global::j4n.IA {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_m10;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_main1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorA2;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public A() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::j4n.A.staticClass, global::j4n.A.j4n__ctorA2, this);
            }
        }
        
        protected A(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::j4n.A.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::j4n.A.staticClass = @__class;
            global::j4n.A.j4n_m10 = @__env.GetMethodID(global::j4n.A.staticClass, "m1", "()V");
            global::j4n.A.j4n_main1 = @__env.GetStaticMethodID(global::j4n.A.staticClass, "main", "([Ljava/lang/String;)V");
            global::j4n.A.j4n__ctorA2 = @__env.GetMethodID(global::j4n.A.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void m1() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::j4n.A.j4n_m10);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("([Ljava/lang/String;)V")]
        public static void main(global::java.lang.String[] par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallStaticVoidMethod(global::j4n.A.staticClass, global::j4n.A.j4n_main1, global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par0));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::j4n.A(@__env);
            }
        }
    }
    #endregion
}
