// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system.windows.forms;

@net.sf.jni4net.attributes.ClrType
public class Application extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Application(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected Application() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native static boolean getAllowQuit();
    
    @net.sf.jni4net.attributes.ClrMethod("()LMicrosoft/Win32/RegistryKey;")
    public native static system.MarshalByRefObject getCommonAppDataRegistry();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native static java.lang.String getCommonAppDataPath();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native static java.lang.String getCompanyName();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Globalization/CultureInfo;")
    public native static system.Object getCurrentCulture();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Globalization/CultureInfo;)V")
    public native static void setCurrentCulture(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/InputLanguage;")
    public native static system.Object getCurrentInputLanguage();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/InputLanguage;)V")
    public native static void setCurrentInputLanguage(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native static java.lang.String getExecutablePath();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native static java.lang.String getLocalUserAppDataPath();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native static boolean getMessageLoop();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/FormCollection;")
    public native static system.Object getOpenForms();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native static java.lang.String getProductName();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native static java.lang.String getProductVersion();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Application+MessageLoopCallback;)V")
    public native static void RegisterMessageLoop(system.MulticastDelegate callback);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native static boolean getRenderWithVisualStyles();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native static java.lang.String getSafeTopLevelCaptionFormat();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native static void setSafeTopLevelCaptionFormat(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native static java.lang.String getStartupPath();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native static void UnregisterMessageLoop();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native static boolean getUseWaitCursor();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native static void setUseWaitCursor(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native static java.lang.String getUserAppDataPath();
    
    @net.sf.jni4net.attributes.ClrMethod("()LMicrosoft/Win32/RegistryKey;")
    public native static system.MarshalByRefObject getUserAppDataRegistry();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/VisualStyles/VisualStyleState;")
    public native static system.Enum getVisualStyleState();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/VisualStyles/VisualStyleState;)V")
    public native static void setVisualStyleState(system.Enum value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native static void addApplicationExit(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native static void removeApplicationExit(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/IMessageFilter;)V")
    public native static void AddMessageFilter(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Message;)Z")
    public native static boolean FilterMessage(net.sf.jni4net.Ref<system.windows.forms.Message> message);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native static void addIdle(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native static void removeIdle(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native static void addEnterThreadModal(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native static void removeEnterThreadModal(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native static void addLeaveThreadModal(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native static void removeLeaveThreadModal(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Threading/ThreadExceptionEventHandler;)V")
    public native static void addThreadException(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Threading/ThreadExceptionEventHandler;)V")
    public native static void removeThreadException(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native static void addThreadExit(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native static void removeThreadExit(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native static void DoEvents();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native static void EnableVisualStyles();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native static void Exit();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/CancelEventArgs;)V")
    public native static void Exit(system.EventArgs e);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native static void ExitThread();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Threading/ApartmentState;")
    public native static system.Enum OleRequired();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Exception;)V")
    public native static void OnThreadException(system.Exception t);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventArgs;)V")
    public native static void RaiseIdle(system.EventArgs e);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/IMessageFilter;)V")
    public native static void RemoveMessageFilter(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native static void Restart();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native static void Run();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Form;)V")
    public native static void Run(system.windows.forms.Form mainForm);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/ApplicationContext;)V")
    public native static void Run(system.Object context);
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native static void SetCompatibleTextRenderingDefault(boolean defaultValue);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/PowerState;ZZ)Z")
    public native static boolean SetSuspendState(system.Enum state, boolean force, boolean disableWakeEvent);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/UnhandledExceptionMode;)V")
    public native static void SetUnhandledExceptionMode(system.Enum mode);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/UnhandledExceptionMode;Z)V")
    public native static void SetUnhandledExceptionMode(system.Enum mode, boolean threadScope);
    
    public static system.Type typeof() {
        return system.windows.forms.Application.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        system.windows.forms.Application.staticType = staticType;
    }
    //</generated-proxy>
}
