// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system.windows.forms;

@net.sf.jni4net.attributes.ClrType
public class AutoScaleMode extends system.Enum {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected AutoScaleMode(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected AutoScaleMode() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    public static system.Type typeof() {
        return system.windows.forms.AutoScaleMode.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        system.windows.forms.AutoScaleMode.staticType = staticType;
    }
    //</generated-proxy>
}
