// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system.windows.forms;

@net.sf.jni4net.attributes.ClrType
public class Control extends system.componentmodel.Component {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Control(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public Control() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        system.windows.forms.Control.__ctorControl0(this);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/String;)V")
    public Control(java.lang.String text) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        system.windows.forms.Control.__ctorControl1(this, text);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/String;IIII)V")
    public Control(java.lang.String text, int left, int top, int width, int height) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        system.windows.forms.Control.__ctorControl2(this, text, left, top, width, height);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/Windows/Forms/Control;LSystem/String;)V")
    public Control(system.windows.forms.Control parent, java.lang.String text) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        system.windows.forms.Control.__ctorControl3(this, parent, text);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/Windows/Forms/Control;LSystem/String;IIII)V")
    public Control(system.windows.forms.Control parent, java.lang.String text, int left, int top, int width, int height) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        system.windows.forms.Control.__ctorControl4(this, parent, text, left, top, width, height);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorControl0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)V")
    private native static void __ctorControl1(net.sf.jni4net.inj.IClrProxy thiz, java.lang.String text);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;IIII)V")
    private native static void __ctorControl2(net.sf.jni4net.inj.IClrProxy thiz, java.lang.String text, int left, int top, int width, int height);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lsystem/windows/forms/Control;Ljava/lang/String;)V")
    private native static void __ctorControl3(net.sf.jni4net.inj.IClrProxy thiz, system.windows.forms.Control parent, java.lang.String text);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lsystem/windows/forms/Control;Ljava/lang/String;IIII)V")
    private native static void __ctorControl4(net.sf.jni4net.inj.IClrProxy thiz, system.windows.forms.Control parent, java.lang.String text, int left, int top, int width, int height);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/DragEventArgs;)V")
    public native void OnDragEnter(system.EventArgs e);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventArgs;)V")
    public native void OnDragLeave(system.EventArgs e);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/DragEventArgs;)V")
    public native void OnDragDrop(system.EventArgs e);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/DragEventArgs;)V")
    public native void OnDragOver(system.EventArgs e);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getInvokeRequired();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Delegate;[LSystem/Object;)LSystem/IAsyncResult;")
    public native system.IAsyncResult BeginInvoke(system.Delegate method, system.Object[] args);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/IAsyncResult;)LSystem/Object;")
    public native system.Object EndInvoke(system.IAsyncResult result);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Delegate;[LSystem/Object;)LSystem/Object;")
    public native system.Object Invoke(system.Delegate method, system.Object[] args);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/IntPtr;")
    public native long getHandle();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/ControlBindingsCollection;")
    public native system.MarshalByRefObject getDataBindings();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/BindingContext;")
    public native system.Object getBindingContext();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/BindingContext;)V")
    public native void setBindingContext(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/AccessibleObject;")
    public native system.MarshalByRefObject getAccessibilityObject();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getAccessibleDefaultActionDescription();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setAccessibleDefaultActionDescription(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getAccessibleDescription();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setAccessibleDescription(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getAccessibleName();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setAccessibleName(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/AccessibleRole;")
    public native system.Enum getAccessibleRole();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/AccessibleRole;)V")
    public native void setAccessibleRole(system.Enum value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getAllowDrop();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setAllowDrop(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/AnchorStyles;")
    public native system.Enum getAnchor();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/AnchorStyles;)V")
    public native void setAnchor(system.Enum value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getAutoSize();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setAutoSize(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addAutoSizeChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeAutoSizeChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Point;")
    public native system.drawing.Point getAutoScrollOffset();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Point;)V")
    public native void setAutoScrollOffset(system.drawing.Point value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/Layout/LayoutEngine;")
    public native system.Object getLayoutEngine();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Color;")
    public native system.ValueType getBackColor();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Color;)V")
    public native void setBackColor(system.ValueType value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addBackColorChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeBackColorChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Image;")
    public native system.MarshalByRefObject getBackgroundImage();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Image;)V")
    public native void setBackgroundImage(system.MarshalByRefObject value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addBackgroundImageChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeBackgroundImageChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/ImageLayout;")
    public native system.Enum getBackgroundImageLayout();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/ImageLayout;)V")
    public native void setBackgroundImageLayout(system.Enum value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addBackgroundImageLayoutChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeBackgroundImageLayoutChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void ResetBindings();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addBindingContextChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeBindingContextChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getBottom();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Rectangle;")
    public native system.ValueType getBounds();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Rectangle;)V")
    public native void setBounds(system.ValueType value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getCanFocus();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getCanSelect();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getCapture();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setCapture(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getCausesValidation();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setCausesValidation(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addCausesValidationChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeCausesValidationChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native static boolean getCheckForIllegalCrossThreadCalls();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native static void setCheckForIllegalCrossThreadCalls(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Rectangle;")
    public native system.ValueType getClientRectangle();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Size;")
    public native system.drawing.Size getClientSize();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Size;)V")
    public native void setClientSize(system.drawing.Size value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addClientSizeChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeClientSizeChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getCompanyName();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getContainsFocus();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/ContextMenu;")
    public native system.componentmodel.Component getContextMenu();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/ContextMenu;)V")
    public native void setContextMenu(system.componentmodel.Component value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addContextMenuChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeContextMenuChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/ContextMenuStrip;")
    public native system.windows.forms.ScrollableControl getContextMenuStrip();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/ContextMenuStrip;)V")
    public native void setContextMenuStrip(system.windows.forms.ScrollableControl value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addContextMenuStripChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeContextMenuStripChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/Control+ControlCollection;")
    public native system.windows.forms.layout.ArrangedElementCollection getControls();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getCreated();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/Cursor;")
    public native system.Object getCursor();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Cursor;)V")
    public native void setCursor(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addCursorChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeCursorChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Color;")
    public native static system.ValueType getDefaultBackColor();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Font;")
    public native static system.MarshalByRefObject getDefaultFont();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Color;")
    public native static system.ValueType getDefaultForeColor();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Rectangle;")
    public native system.ValueType getDisplayRectangle();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isDisposed();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getDisposing();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/DockStyle;")
    public native system.Enum getDock();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/DockStyle;)V")
    public native void setDock(system.Enum value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addDockChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeDockChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getEnabled();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setEnabled(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addEnabledChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeEnabledChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getFocused();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Font;")
    public native system.MarshalByRefObject getFont();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Font;)V")
    public native void setFont(system.MarshalByRefObject value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addFontChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeFontChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Color;")
    public native system.ValueType getForeColor();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Color;)V")
    public native void setForeColor(system.ValueType value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addForeColorChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeForeColorChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Size;)LSystem/Drawing/Size;")
    public native system.drawing.Size GetPreferredSize(system.drawing.Size proposedSize);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getHasChildren();
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getHeight();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setHeight(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isHandleCreated();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isAccessible();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setIsAccessible(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isMirrored();
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getLeft();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setLeft(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Point;")
    public native system.drawing.Point getLocation();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Point;)V")
    public native void setLocation(system.drawing.Point value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addLocationChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeLocationChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/Padding;")
    public native system.ValueType getMargin();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Padding;)V")
    public native void setMargin(system.ValueType value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addMarginChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeMarginChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Size;")
    public native system.drawing.Size getMaximumSize();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Size;)V")
    public native void setMaximumSize(system.drawing.Size value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Size;")
    public native system.drawing.Size getMinimumSize();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Size;)V")
    public native void setMinimumSize(system.drawing.Size value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/Keys;")
    public native static system.Enum getModifierKeys();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/MouseButtons;")
    public native static system.Enum getMouseButtons();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Point;")
    public native static system.drawing.Point getMousePosition();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getName();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setName(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/Control;")
    public native system.windows.forms.Control getParent();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Control;)V")
    public native void setParent(system.windows.forms.Control value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getProductName();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getProductVersion();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getRecreatingHandle();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Region;")
    public native system.MarshalByRefObject getRegion();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Region;)V")
    public native void setRegion(system.MarshalByRefObject value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addRegionChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeRegionChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getRight();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/RightToLeft;")
    public native system.Enum getRightToLeft();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/RightToLeft;)V")
    public native void setRightToLeft(system.Enum value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addRightToLeftChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeRightToLeftChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Size;")
    public native system.drawing.Size getSize();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Size;)V")
    public native void setSize(system.drawing.Size value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addSizeChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeSizeChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getTabIndex();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setTabIndex(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addTabIndexChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeTabIndexChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getTabStop();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setTabStop(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addTabStopChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeTabStopChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Object;")
    public native system.Object getTag();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)V")
    public native void setTag(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getText();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setText(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addTextChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeTextChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getTop();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setTop(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/Control;")
    public native system.windows.forms.Control getTopLevelControl();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getUseWaitCursor();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setUseWaitCursor(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getVisible();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setVisible(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addVisibleChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeVisibleChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getWidth();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setWidth(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/IWindowTarget;")
    public native system.Object getWindowTarget();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/IWindowTarget;)V")
    public native void setWindowTarget(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addClick(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeClick(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/ControlEventHandler;)V")
    public native void addControlAdded(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/ControlEventHandler;)V")
    public native void removeControlAdded(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/ControlEventHandler;)V")
    public native void addControlRemoved(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/ControlEventHandler;)V")
    public native void removeControlRemoved(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/DragEventHandler;)V")
    public native void addDragDrop(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/DragEventHandler;)V")
    public native void removeDragDrop(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/DragEventHandler;)V")
    public native void addDragEnter(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/DragEventHandler;)V")
    public native void removeDragEnter(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/DragEventHandler;)V")
    public native void addDragOver(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/DragEventHandler;)V")
    public native void removeDragOver(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addDragLeave(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeDragLeave(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/GiveFeedbackEventHandler;)V")
    public native void addGiveFeedback(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/GiveFeedbackEventHandler;)V")
    public native void removeGiveFeedback(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addHandleCreated(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeHandleCreated(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addHandleDestroyed(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeHandleDestroyed(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/HelpEventHandler;)V")
    public native void addHelpRequested(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/HelpEventHandler;)V")
    public native void removeHelpRequested(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/InvalidateEventHandler;)V")
    public native void addInvalidated(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/InvalidateEventHandler;)V")
    public native void removeInvalidated(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Size;")
    public native system.drawing.Size getPreferredSize();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/Padding;")
    public native system.ValueType getPadding();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Padding;)V")
    public native void setPadding(system.ValueType value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addPaddingChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removePaddingChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/PaintEventHandler;)V")
    public native void addPaint(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/PaintEventHandler;)V")
    public native void removePaint(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/QueryContinueDragEventHandler;)V")
    public native void addQueryContinueDrag(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/QueryContinueDragEventHandler;)V")
    public native void removeQueryContinueDrag(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/QueryAccessibilityHelpEventHandler;)V")
    public native void addQueryAccessibilityHelp(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/QueryAccessibilityHelpEventHandler;)V")
    public native void removeQueryAccessibilityHelp(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addDoubleClick(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeDoubleClick(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addEnter(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeEnter(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addGotFocus(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeGotFocus(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/KeyEventHandler;)V")
    public native void addKeyDown(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/KeyEventHandler;)V")
    public native void removeKeyDown(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/KeyPressEventHandler;)V")
    public native void addKeyPress(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/KeyPressEventHandler;)V")
    public native void removeKeyPress(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/KeyEventHandler;)V")
    public native void addKeyUp(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/KeyEventHandler;)V")
    public native void removeKeyUp(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/LayoutEventHandler;)V")
    public native void addLayout(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/LayoutEventHandler;)V")
    public native void removeLayout(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addLeave(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeLeave(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addLostFocus(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeLostFocus(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/MouseEventHandler;)V")
    public native void addMouseClick(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/MouseEventHandler;)V")
    public native void removeMouseClick(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/MouseEventHandler;)V")
    public native void addMouseDoubleClick(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/MouseEventHandler;)V")
    public native void removeMouseDoubleClick(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addMouseCaptureChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeMouseCaptureChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/MouseEventHandler;)V")
    public native void addMouseDown(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/MouseEventHandler;)V")
    public native void removeMouseDown(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addMouseEnter(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeMouseEnter(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addMouseLeave(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeMouseLeave(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addMouseHover(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeMouseHover(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/MouseEventHandler;)V")
    public native void addMouseMove(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/MouseEventHandler;)V")
    public native void removeMouseMove(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/MouseEventHandler;)V")
    public native void addMouseUp(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/MouseEventHandler;)V")
    public native void removeMouseUp(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/MouseEventHandler;)V")
    public native void addMouseWheel(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/MouseEventHandler;)V")
    public native void removeMouseWheel(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addMove(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeMove(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/PreviewKeyDownEventHandler;)V")
    public native void addPreviewKeyDown(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/PreviewKeyDownEventHandler;)V")
    public native void removePreviewKeyDown(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addResize(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeResize(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/UICuesEventHandler;)V")
    public native void addChangeUICues(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/UICuesEventHandler;)V")
    public native void removeChangeUICues(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addStyleChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeStyleChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addSystemColorsChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeSystemColorsChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/CancelEventHandler;)V")
    public native void addValidating(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/CancelEventHandler;)V")
    public native void removeValidating(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addValidated(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeValidated(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addParentChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeParentChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Delegate;)LSystem/IAsyncResult;")
    public native system.IAsyncResult BeginInvoke(system.Delegate method);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void BringToFront();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Control;)Z")
    public native boolean Contains(system.windows.forms.Control ctl);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Graphics;")
    public native system.MarshalByRefObject CreateGraphics();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void CreateControl();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LSystem/Windows/Forms/DragDropEffects;)LSystem/Windows/Forms/DragDropEffects;")
    public native system.Enum DoDragDrop(system.Object data, system.Enum allowedEffects);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Bitmap;LSystem/Drawing/Rectangle;)V")
    public native void DrawToBitmap(system.MarshalByRefObject bitmap, system.ValueType targetBounds);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/Form;")
    public native system.windows.forms.Form FindForm();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean Focus();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/IntPtr;)LSystem/Windows/Forms/Control;")
    public native static system.windows.forms.Control FromChildHandle(long handle);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/IntPtr;)LSystem/Windows/Forms/Control;")
    public native static system.windows.forms.Control FromHandle(long handle);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Point;LSystem/Windows/Forms/GetChildAtPointSkip;)LSystem/Windows/Forms/Control;")
    public native system.windows.forms.Control GetChildAtPoint(system.drawing.Point pt, system.Enum skipValue);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Point;)LSystem/Windows/Forms/Control;")
    public native system.windows.forms.Control GetChildAtPoint(system.drawing.Point pt);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/IContainerControl;")
    public native system.Object GetContainerControl();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Control;Z)LSystem/Windows/Forms/Control;")
    public native system.windows.forms.Control GetNextControl(system.windows.forms.Control ctl, boolean forward);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void Hide();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Region;)V")
    public native void Invalidate(system.MarshalByRefObject region);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Region;Z)V")
    public native void Invalidate(system.MarshalByRefObject region, boolean invalidateChildren);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void Invalidate();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void Invalidate(boolean invalidateChildren);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Rectangle;)V")
    public native void Invalidate(system.ValueType rc);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Rectangle;Z)V")
    public native void Invalidate(system.ValueType rc, boolean invalidateChildren);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Delegate;)LSystem/Object;")
    public native system.Object Invoke(system.Delegate method);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Keys;)Z")
    public native static boolean IsKeyLocked(system.Enum keyVal);
    
    @net.sf.jni4net.attributes.ClrMethod("(CLSystem/String;)Z")
    public native static boolean IsMnemonic(char charCode, java.lang.String text);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void PerformLayout();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Control;LSystem/String;)V")
    public native void PerformLayout(system.windows.forms.Control affectedControl, java.lang.String affectedProperty);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Point;)LSystem/Drawing/Point;")
    public native system.drawing.Point PointToClient(system.drawing.Point p);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Point;)LSystem/Drawing/Point;")
    public native system.drawing.Point PointToScreen(system.drawing.Point p);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Message;)Z")
    public native boolean PreProcessMessage(net.sf.jni4net.Ref<system.windows.forms.Message> msg);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Message;)LSystem/Windows/Forms/PreProcessControlState;")
    public native system.Enum PreProcessControlMessage(net.sf.jni4net.Ref<system.windows.forms.Message> msg);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void ResetBackColor();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void ResetCursor();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void ResetFont();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void ResetForeColor();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void ResetRightToLeft();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Rectangle;)LSystem/Drawing/Rectangle;")
    public native system.ValueType RectangleToClient(system.ValueType r);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Rectangle;)LSystem/Drawing/Rectangle;")
    public native system.ValueType RectangleToScreen(system.ValueType r);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void Refresh();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void ResetText();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void ResumeLayout();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void ResumeLayout(boolean performLayout);
    
    @net.sf.jni4net.attributes.ClrMethod("(F)V")
    public native void Scale(float ratio);
    
    @net.sf.jni4net.attributes.ClrMethod("(FF)V")
    public native void Scale(float dx, float dy);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/SizeF;)V")
    public native void Scale(system.drawing.SizeF factor);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void Select();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Control;ZZZZ)Z")
    public native boolean SelectNextControl(system.windows.forms.Control ctl, boolean forward, boolean tabStopOnly, boolean nested, boolean wrap);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void SendToBack();
    
    @net.sf.jni4net.attributes.ClrMethod("(IIII)V")
    public native void SetBounds(int x, int y, int width, int height);
    
    @net.sf.jni4net.attributes.ClrMethod("(IIIILSystem/Windows/Forms/BoundsSpecified;)V")
    public native void SetBounds(int x, int y, int width, int height, system.Enum specified);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void Show();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void SuspendLayout();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void Update();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/ImeMode;")
    public native system.Enum getImeMode();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/ImeMode;)V")
    public native void setImeMode(system.Enum value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addImeModeChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeImeModeChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void ResetImeMode();
    
    public static system.Type typeof() {
        return system.windows.forms.Control.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        system.windows.forms.Control.staticType = staticType;
    }
    //</generated-proxy>
}
