// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system.windows.forms;

@net.sf.jni4net.attributes.ClrType
public class Form extends system.windows.forms.ContainerControl {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Form(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public Form() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        system.windows.forms.Form.__ctorForm0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorForm0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/IButtonControl;")
    public native system.Object getAcceptButton();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/IButtonControl;)V")
    public native void setAcceptButton(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/Form;")
    public native static system.windows.forms.Form getActiveForm();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/Form;")
    public native system.windows.forms.Form getActiveMdiChild();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getAllowTransparency();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setAllowTransparency(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getAutoScale();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setAutoScale(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Size;")
    public native system.drawing.Size getAutoScaleBaseSize();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Size;)V")
    public native void setAutoScaleBaseSize(system.drawing.Size value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/AutoSizeMode;")
    public native system.Enum getAutoSizeMode();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/AutoSizeMode;)V")
    public native void setAutoSizeMode(system.Enum value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/FormBorderStyle;")
    public native system.Enum getFormBorderStyle();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/FormBorderStyle;)V")
    public native void setFormBorderStyle(system.Enum value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/IButtonControl;")
    public native system.Object getCancelButton();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/IButtonControl;)V")
    public native void setCancelButton(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getControlBox();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setControlBox(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Rectangle;")
    public native system.ValueType getDesktopBounds();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Rectangle;)V")
    public native void setDesktopBounds(system.ValueType value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Point;")
    public native system.drawing.Point getDesktopLocation();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Point;)V")
    public native void setDesktopLocation(system.drawing.Point value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/DialogResult;")
    public native system.Enum getDialogResult();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/DialogResult;)V")
    public native void setDialogResult(system.Enum value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getHelpButton();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setHelpButton(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/CancelEventHandler;)V")
    public native void addHelpButtonClicked(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/CancelEventHandler;)V")
    public native void removeHelpButtonClicked(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Icon;")
    public native system.MarshalByRefObject getIcon();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Icon;)V")
    public native void setIcon(system.MarshalByRefObject value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isMdiChild();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isMdiContainer();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setIsMdiContainer(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isRestrictedWindow();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getKeyPreview();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setKeyPreview(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addMaximizedBoundsChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeMaximizedBoundsChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addMaximumSizeChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeMaximumSizeChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/MenuStrip;")
    public native system.windows.forms.ScrollableControl getMainMenuStrip();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/MenuStrip;)V")
    public native void setMainMenuStrip(system.windows.forms.ScrollableControl value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/MainMenu;")
    public native system.componentmodel.Component getMenu();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/MainMenu;)V")
    public native void setMenu(system.componentmodel.Component value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addMinimumSizeChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeMinimumSizeChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getMaximizeBox();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setMaximizeBox(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()[LSystem/Windows/Forms/Form;")
    public native system.windows.forms.Form[] getMdiChildren();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/Form;")
    public native system.windows.forms.Form getMdiParent();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Form;)V")
    public native void setMdiParent(system.windows.forms.Form value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/MainMenu;")
    public native system.componentmodel.Component getMergedMenu();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getMinimizeBox();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setMinimizeBox(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getModal();
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getOpacity();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setOpacity(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()[LSystem/Windows/Forms/Form;")
    public native system.windows.forms.Form[] getOwnedForms();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/Form;")
    public native system.windows.forms.Form getOwner();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Form;)V")
    public native void setOwner(system.windows.forms.Form value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Rectangle;")
    public native system.ValueType getRestoreBounds();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getRightToLeftLayout();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setRightToLeftLayout(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getShowInTaskbar();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setShowInTaskbar(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getShowIcon();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setShowIcon(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/SizeGripStyle;")
    public native system.Enum getSizeGripStyle();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/SizeGripStyle;)V")
    public native void setSizeGripStyle(system.Enum value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/FormStartPosition;")
    public native system.Enum getStartPosition();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/FormStartPosition;)V")
    public native void setStartPosition(system.Enum value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getTopLevel();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setTopLevel(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getTopMost();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setTopMost(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Color;")
    public native system.ValueType getTransparencyKey();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Color;)V")
    public native void setTransparencyKey(system.ValueType value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/FormWindowState;")
    public native system.Enum getWindowState();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/FormWindowState;)V")
    public native void setWindowState(system.Enum value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addActivated(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeActivated(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/CancelEventHandler;)V")
    public native void addClosing(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/CancelEventHandler;)V")
    public native void removeClosing(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addClosed(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeClosed(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addDeactivate(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeDeactivate(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/FormClosingEventHandler;)V")
    public native void addFormClosing(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/FormClosingEventHandler;)V")
    public native void removeFormClosing(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/FormClosedEventHandler;)V")
    public native void addFormClosed(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/FormClosedEventHandler;)V")
    public native void removeFormClosed(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addLoad(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeLoad(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addMdiChildActivate(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeMdiChildActivate(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addMenuComplete(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeMenuComplete(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addMenuStart(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeMenuStart(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/InputLanguageChangedEventHandler;)V")
    public native void addInputLanguageChanged(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/InputLanguageChangedEventHandler;)V")
    public native void removeInputLanguageChanged(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/InputLanguageChangingEventHandler;)V")
    public native void addInputLanguageChanging(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/InputLanguageChangingEventHandler;)V")
    public native void removeInputLanguageChanging(system.MulticastDelegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addRightToLeftLayoutChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeRightToLeftLayoutChanged(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addShown(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeShown(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void Activate();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Form;)V")
    public native void AddOwnedForm(system.windows.forms.Form ownedForm);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void Close();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Font;)LSystem/Drawing/SizeF;")
    public native static system.drawing.SizeF GetAutoScaleSize(system.MarshalByRefObject font);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/MdiLayout;)V")
    public native void LayoutMdi(system.Enum value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/Form;)V")
    public native void RemoveOwnedForm(system.windows.forms.Form ownedForm);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addResizeBegin(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeResizeBegin(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void addResizeEnd(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/EventHandler;)V")
    public native void removeResizeEnd(system.EventHandler value);
    
    @net.sf.jni4net.attributes.ClrMethod("(IIII)V")
    public native void SetDesktopBounds(int x, int y, int width, int height);
    
    @net.sf.jni4net.attributes.ClrMethod("(II)V")
    public native void SetDesktopLocation(int x, int y);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/IWin32Window;)V")
    public native void Show(system.Object owner);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/DialogResult;")
    public native system.Enum ShowDialog();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Windows/Forms/IWin32Window;)LSystem/Windows/Forms/DialogResult;")
    public native system.Enum ShowDialog(system.Object owner);
    
    public static system.Type typeof() {
        return system.windows.forms.Form.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        system.windows.forms.Form.staticType = staticType;
    }
    //</generated-proxy>
}
