// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system.windows.forms;

@net.sf.jni4net.attributes.ClrType
public class Message extends system.ValueType {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Message(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected Message() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/IntPtr;")
    public native long getHWnd();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/IntPtr;)V")
    public native void setHWnd(long value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getMsg();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setMsg(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/IntPtr;")
    public native long getWParam();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/IntPtr;)V")
    public native void setWParam(long value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/IntPtr;")
    public native long getLParam();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/IntPtr;)V")
    public native void setLParam(long value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/IntPtr;")
    public native long getResult();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/IntPtr;)V")
    public native void setResult(long value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Type;)LSystem/Object;")
    public native system.Object GetLParam(system.Type cls);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/IntPtr;ILSystem/IntPtr;LSystem/IntPtr;)LSystem/Windows/Forms/Message;")
    public native static system.windows.forms.Message Create(long hWnd, int msg, long wparam, long lparam);
    
    public static system.Type typeof() {
        return system.windows.forms.Message.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        system.windows.forms.Message.staticType = staticType;
    }
    //</generated-proxy>
}
