//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Forms {
    
    
    #region Component Designer generated code 
    public partial class Button_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::System.Windows.Forms.@__Button.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::System.Windows.Forms.Button), typeof(global::System.Windows.Forms.Button_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::System.Windows.Forms.Button), typeof(global::System.Windows.Forms.Button_))]
    internal sealed partial class @__Button : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__Button(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::System.Windows.Forms.@__Button.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__Button);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getDialogResult", "DialogResult0", "()Lsystem/Enum;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setDialogResult", "DialogResult1", "(Lsystem/Enum;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "NotifyDefault", "NotifyDefault2", "(Z)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "PerformClick", "PerformClick3", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAutoSizeMode", "AutoSizeMode4", "()Lsystem/Enum;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setAutoSizeMode", "AutoSizeMode5", "(Lsystem/Enum;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorButton0", "__ctorButton0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle DialogResult0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/Enum;
            // ()LSystem/Windows/Forms/DialogResult;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.Button @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Button>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Windows.Forms.DialogResult>(@__env, ((global::System.Windows.Forms.IButtonControl)(@__real)).DialogResult);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void DialogResult1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Enum;)V
            // (LSystem/Windows/Forms/DialogResult;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.Button @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Button>(@__env, @__obj);
            ((global::System.Windows.Forms.IButtonControl)(@__real)).DialogResult = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.DialogResult>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void NotifyDefault2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, bool value) {
            // (Z)V
            // (Z)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.Button @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Button>(@__env, @__obj);
            ((global::System.Windows.Forms.IButtonControl)(@__real)).NotifyDefault(value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void PerformClick3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.Button @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Button>(@__env, @__obj);
            ((global::System.Windows.Forms.IButtonControl)(@__real)).PerformClick();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle AutoSizeMode4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/Enum;
            // ()LSystem/Windows/Forms/AutoSizeMode;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.Button @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Button>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Windows.Forms.AutoSizeMode>(@__env, @__real.AutoSizeMode);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void AutoSizeMode5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Enum;)V
            // (LSystem/Windows/Forms/AutoSizeMode;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.Button @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Button>(@__env, @__obj);
            @__real.AutoSizeMode = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.AutoSizeMode>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorButton0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.Button @__real = new global::System.Windows.Forms.Button();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::System.Windows.Forms.@__Button(@__env);
            }
        }
    }
    #endregion
}
