//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Forms {
    
    
    #region Component Designer generated code 
    public partial class ContainerControl_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::System.Windows.Forms.@__ContainerControl.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::System.Windows.Forms.ContainerControl), typeof(global::System.Windows.Forms.ContainerControl_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::System.Windows.Forms.ContainerControl), typeof(global::System.Windows.Forms.ContainerControl_))]
    internal sealed partial class @__ContainerControl : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__ContainerControl(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::System.Windows.Forms.@__ContainerControl.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__ContainerControl);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getActiveControl", "ActiveControl0", "()Lsystem/windows/forms/Control;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setActiveControl", "ActiveControl1", "(Lsystem/windows/forms/Control;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ActivateControl", "ActivateControl2", "(Lsystem/windows/forms/Control;)Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAutoScaleDimensions", "AutoScaleDimensions3", "()Lsystem/drawing/SizeF;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setAutoScaleDimensions", "AutoScaleDimensions4", "(Lsystem/drawing/SizeF;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAutoScaleMode", "AutoScaleMode5", "()Lsystem/windows/forms/AutoScaleMode;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setAutoScaleMode", "AutoScaleMode6", "(Lsystem/windows/forms/AutoScaleMode;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAutoValidate", "AutoValidate7", "()Lsystem/Enum;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setAutoValidate", "AutoValidate8", "(Lsystem/Enum;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "addAutoValidateChanged", "AutoValidateChanged9", "(Lsystem/EventHandler;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "removeAutoValidateChanged", "AutoValidateChanged10", "(Lsystem/EventHandler;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getCurrentAutoScaleDimensions", "CurrentAutoScaleDimensions11", "()Lsystem/drawing/SizeF;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getParentForm", "ParentForm12", "()Lsystem/windows/forms/Form;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "PerformAutoScale", "PerformAutoScale13", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Validate", "Validate14", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Validate", "Validate15", "(Z)Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ValidateChildren", "ValidateChildren16", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ValidateChildren", "ValidateChildren17", "(Lsystem/Enum;)Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorContainerControl0", "__ctorContainerControl0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ActiveControl0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/windows/forms/Control;
            // ()LSystem/Windows/Forms/Control;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Windows.Forms.Control>(@__env, ((global::System.Windows.Forms.IContainerControl)(@__real)).ActiveControl);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void ActiveControl1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/windows/forms/Control;)V
            // (LSystem/Windows/Forms/Control;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            ((global::System.Windows.Forms.IContainerControl)(@__real)).ActiveControl = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Control>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static bool ActivateControl2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle active) {
            // (Lsystem/windows/forms/Control;)Z
            // (LSystem/Windows/Forms/Control;)Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__return = ((bool)(((global::System.Windows.Forms.IContainerControl)(@__real)).ActivateControl(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Control>(@__env, active))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle AutoScaleDimensions3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/drawing/SizeF;
            // ()LSystem/Drawing/SizeF;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Drawing.SizeF>(@__env, @__real.AutoScaleDimensions);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void AutoScaleDimensions4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/drawing/SizeF;)V
            // (LSystem/Drawing/SizeF;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__real.AutoScaleDimensions = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.SizeF>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle AutoScaleMode5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/windows/forms/AutoScaleMode;
            // ()LSystem/Windows/Forms/AutoScaleMode;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Windows.Forms.AutoScaleMode>(@__env, @__real.AutoScaleMode);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void AutoScaleMode6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/windows/forms/AutoScaleMode;)V
            // (LSystem/Windows/Forms/AutoScaleMode;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__real.AutoScaleMode = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.AutoScaleMode>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle AutoValidate7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/Enum;
            // ()LSystem/Windows/Forms/AutoValidate;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Windows.Forms.AutoValidate>(@__env, @__real.AutoValidate);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void AutoValidate8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Enum;)V
            // (LSystem/Windows/Forms/AutoValidate;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__real.AutoValidate = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.AutoValidate>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void AutoValidateChanged9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/EventHandler;)V
            // (LSystem/EventHandler;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__real.AutoValidateChanged += global::net.sf.jni4net.utils.Convertor.StrongJ2CpDelegate<global::System.EventHandler>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void AutoValidateChanged10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/EventHandler;)V
            // (LSystem/EventHandler;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__real.AutoValidateChanged -= global::net.sf.jni4net.utils.Convertor.StrongJ2CpDelegate<global::System.EventHandler>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle CurrentAutoScaleDimensions11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/drawing/SizeF;
            // ()LSystem/Drawing/SizeF;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Drawing.SizeF>(@__env, @__real.CurrentAutoScaleDimensions);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ParentForm12(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/windows/forms/Form;
            // ()LSystem/Windows/Forms/Form;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Windows.Forms.Form>(@__env, @__real.ParentForm);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void PerformAutoScale13(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__real.PerformAutoScale();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static bool Validate14(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__return = ((bool)(@__real.Validate()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool Validate15(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, bool checkAutoValidate) {
            // (Z)Z
            // (Z)Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__return = ((bool)(@__real.Validate(checkAutoValidate)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool ValidateChildren16(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__return = ((bool)(@__real.ValidateChildren()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool ValidateChildren17(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle validationConstraints) {
            // (Lsystem/Enum;)Z
            // (LSystem/Windows/Forms/ValidationConstraints;)Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.Windows.Forms.ContainerControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ContainerControl>(@__env, @__obj);
            @__return = ((bool)(@__real.ValidateChildren(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ValidationConstraints>(@__env, validationConstraints))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void @__ctorContainerControl0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ContainerControl @__real = new global::System.Windows.Forms.ContainerControl();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::System.Windows.Forms.@__ContainerControl(@__env);
            }
        }
    }
    #endregion
}
