//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Forms {
    
    
    #region Component Designer generated code 
    public partial class Message_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::System.Windows.Forms.@__Message.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::System.Windows.Forms.Message), typeof(global::System.Windows.Forms.Message_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::System.Windows.Forms.Message), typeof(global::System.Windows.Forms.Message_))]
    internal sealed partial class @__Message : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__Message(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::System.Windows.Forms.@__Message.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__Message);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getHWnd", "HWnd0", "()J"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setHWnd", "HWnd1", "(J)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getMsg", "Msg2", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setMsg", "Msg3", "(I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getWParam", "WParam4", "()J"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setWParam", "WParam5", "(J)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getLParam", "LParam6", "()J"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setLParam", "LParam7", "(J)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getResult", "Result8", "()J"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setResult", "Result9", "(J)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetLParam", "GetLParam10", "(Lsystem/Type;)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Create", "Create11", "(JIJJ)Lsystem/windows/forms/Message;"));
            return methods;
        }
        
        private static global::System.IntPtr HWnd0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()J
            // ()LSystem/IntPtr;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::System.IntPtr @__return = default(global::System.IntPtr);
            try {
            global::System.Windows.Forms.Message @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Message>(@__env, @__obj);
            @__return = ((global::System.IntPtr)(@__real.HWnd));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void HWnd1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::System.IntPtr value) {
            // (J)V
            // (LSystem/IntPtr;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.Message @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Message>(@__env, @__obj);
            @__real.HWnd = value;
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static int Msg2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Windows.Forms.Message @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Message>(@__env, @__obj);
            @__return = ((int)(@__real.Msg));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Msg3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int value) {
            // (I)V
            // (I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.Message @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Message>(@__env, @__obj);
            @__real.Msg = value;
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::System.IntPtr WParam4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()J
            // ()LSystem/IntPtr;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::System.IntPtr @__return = default(global::System.IntPtr);
            try {
            global::System.Windows.Forms.Message @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Message>(@__env, @__obj);
            @__return = ((global::System.IntPtr)(@__real.WParam));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void WParam5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::System.IntPtr value) {
            // (J)V
            // (LSystem/IntPtr;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.Message @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Message>(@__env, @__obj);
            @__real.WParam = value;
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::System.IntPtr LParam6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()J
            // ()LSystem/IntPtr;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::System.IntPtr @__return = default(global::System.IntPtr);
            try {
            global::System.Windows.Forms.Message @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Message>(@__env, @__obj);
            @__return = ((global::System.IntPtr)(@__real.LParam));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void LParam7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::System.IntPtr value) {
            // (J)V
            // (LSystem/IntPtr;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.Message @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Message>(@__env, @__obj);
            @__real.LParam = value;
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::System.IntPtr Result8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()J
            // ()LSystem/IntPtr;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::System.IntPtr @__return = default(global::System.IntPtr);
            try {
            global::System.Windows.Forms.Message @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Message>(@__env, @__obj);
            @__return = ((global::System.IntPtr)(@__real.Result));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Result9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::System.IntPtr value) {
            // (J)V
            // (LSystem/IntPtr;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.Message @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Message>(@__env, @__obj);
            @__real.Result = value;
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetLParam10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle cls) {
            // (Lsystem/Type;)Lsystem/Object;
            // (LSystem/Type;)LSystem/Object;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.Message @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Message>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<object>(@__env, @__real.GetLParam(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Type>(@__env, cls)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Create11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::System.IntPtr hWnd, int msg, global::System.IntPtr wparam, global::System.IntPtr lparam) {
            // (JIJJ)Lsystem/windows/forms/Message;
            // (LSystem/IntPtr;ILSystem/IntPtr;LSystem/IntPtr;)LSystem/Windows/Forms/Message;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Windows.Forms.Message>(@__env, global::System.Windows.Forms.Message.Create(hWnd, msg, wparam, lparam));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::System.Windows.Forms.@__Message(@__env);
            }
        }
    }
    #endregion
}
