//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Forms {
    
    
    #region Component Designer generated code 
    public partial class ScrollableControl_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::System.Windows.Forms.@__ScrollableControl.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::System.Windows.Forms.ScrollableControl), typeof(global::System.Windows.Forms.ScrollableControl_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::System.Windows.Forms.ScrollableControl), typeof(global::System.Windows.Forms.ScrollableControl_))]
    internal sealed partial class @__ScrollableControl : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__ScrollableControl(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::System.Windows.Forms.@__ScrollableControl.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__ScrollableControl);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAutoScroll", "AutoScroll0", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setAutoScroll", "AutoScroll1", "(Z)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAutoScrollMargin", "AutoScrollMargin2", "()Lsystem/drawing/Size;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setAutoScrollMargin", "AutoScrollMargin3", "(Lsystem/drawing/Size;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAutoScrollPosition", "AutoScrollPosition4", "()Lsystem/drawing/Point;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setAutoScrollPosition", "AutoScrollPosition5", "(Lsystem/drawing/Point;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAutoScrollMinSize", "AutoScrollMinSize6", "()Lsystem/drawing/Size;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setAutoScrollMinSize", "AutoScrollMinSize7", "(Lsystem/drawing/Size;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getHorizontalScroll", "HorizontalScroll8", "()Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getVerticalScroll", "VerticalScroll9", "()Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getDockPadding", "DockPadding10", "()Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ScrollControlIntoView", "ScrollControlIntoView11", "(Lsystem/windows/forms/Control;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "addScroll", "Scroll12", "(Lsystem/MulticastDelegate;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "removeScroll", "Scroll13", "(Lsystem/MulticastDelegate;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "SetAutoScrollMargin", "SetAutoScrollMargin14", "(II)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorScrollableControl0", "__ctorScrollableControl0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static bool AutoScroll0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.Windows.Forms.ScrollableControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ScrollableControl>(@__env, @__obj);
            @__return = ((bool)(@__real.AutoScroll));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void AutoScroll1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, bool value) {
            // (Z)V
            // (Z)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ScrollableControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ScrollableControl>(@__env, @__obj);
            @__real.AutoScroll = value;
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle AutoScrollMargin2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/drawing/Size;
            // ()LSystem/Drawing/Size;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.ScrollableControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ScrollableControl>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Drawing.Size>(@__env, @__real.AutoScrollMargin);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void AutoScrollMargin3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/drawing/Size;)V
            // (LSystem/Drawing/Size;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ScrollableControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ScrollableControl>(@__env, @__obj);
            @__real.AutoScrollMargin = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.Size>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle AutoScrollPosition4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/drawing/Point;
            // ()LSystem/Drawing/Point;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.ScrollableControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ScrollableControl>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Drawing.Point>(@__env, @__real.AutoScrollPosition);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void AutoScrollPosition5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/drawing/Point;)V
            // (LSystem/Drawing/Point;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ScrollableControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ScrollableControl>(@__env, @__obj);
            @__real.AutoScrollPosition = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.Point>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle AutoScrollMinSize6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/drawing/Size;
            // ()LSystem/Drawing/Size;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.ScrollableControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ScrollableControl>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Drawing.Size>(@__env, @__real.AutoScrollMinSize);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void AutoScrollMinSize7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/drawing/Size;)V
            // (LSystem/Drawing/Size;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ScrollableControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ScrollableControl>(@__env, @__obj);
            @__real.AutoScrollMinSize = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.Size>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle HorizontalScroll8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/Object;
            // ()LSystem/Windows/Forms/HScrollProperties;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.ScrollableControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ScrollableControl>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Windows.Forms.HScrollProperties>(@__env, @__real.HorizontalScroll);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle VerticalScroll9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/Object;
            // ()LSystem/Windows/Forms/VScrollProperties;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.ScrollableControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ScrollableControl>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Windows.Forms.VScrollProperties>(@__env, @__real.VerticalScroll);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle DockPadding10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/Object;
            // ()LSystem/Windows/Forms/ScrollableControl+DockPaddingEdges;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Windows.Forms.ScrollableControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ScrollableControl>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Windows.Forms.ScrollableControl.DockPaddingEdges>(@__env, @__real.DockPadding);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void ScrollControlIntoView11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle activeControl) {
            // (Lsystem/windows/forms/Control;)V
            // (LSystem/Windows/Forms/Control;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ScrollableControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ScrollableControl>(@__env, @__obj);
            @__real.ScrollControlIntoView(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.Control>(@__env, activeControl));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Scroll12(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/MulticastDelegate;)V
            // (LSystem/Windows/Forms/ScrollEventHandler;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ScrollableControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ScrollableControl>(@__env, @__obj);
            @__real.Scroll += global::net.sf.jni4net.utils.Convertor.StrongJ2CpDelegate<global::System.Windows.Forms.ScrollEventHandler>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Scroll13(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/MulticastDelegate;)V
            // (LSystem/Windows/Forms/ScrollEventHandler;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ScrollableControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ScrollableControl>(@__env, @__obj);
            @__real.Scroll -= global::net.sf.jni4net.utils.Convertor.StrongJ2CpDelegate<global::System.Windows.Forms.ScrollEventHandler>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void SetAutoScrollMargin14(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int x, int y) {
            // (II)V
            // (II)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ScrollableControl @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Windows.Forms.ScrollableControl>(@__env, @__obj);
            @__real.SetAutoScrollMargin(x, y);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorScrollableControl0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Windows.Forms.ScrollableControl @__real = new global::System.Windows.Forms.ScrollableControl();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::System.Windows.Forms.@__ScrollableControl(@__env);
            }
        }
    }
    #endregion
}
