//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace java.lang {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class Thread : global::java.lang.Object, global::java.lang.Runnable {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_run0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isInterrupted1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_currentThread2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getName3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getThreadGroup4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getStackTrace5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_holdsLock6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_dumpStack7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setDaemon8;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setPriority9;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_start10;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_activeCount11;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_checkAccess12;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_countStackFrames13;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_destroy14;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_enumerate15;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getAllStackTraces16;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getContextClassLoader17;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getDefaultUncaughtExceptionHandler18;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getId19;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getPriority20;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getState21;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getUncaughtExceptionHandler22;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_interrupt23;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_interrupted24;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isAlive25;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isDaemon26;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_join27;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_join28;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_join29;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_resume30;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setContextClassLoader31;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setDefaultUncaughtExceptionHandler32;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setName33;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setUncaughtExceptionHandler34;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_sleep35;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_sleep36;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_stop37;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_stop38;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_suspend39;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_yield40;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_MIN_PRIORITY41;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_NORM_PRIORITY42;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_MAX_PRIORITY43;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorThread44;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorThread45;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorThread46;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorThread47;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorThread48;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorThread49;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorThread50;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorThread51;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Runnable;)V")]
        public Thread(global::java.lang.Runnable par0) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.NewObject(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n__ctorThread44, this, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Runnable>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public Thread() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n__ctorThread45, this);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/ThreadGroup;Ljava/lang/Runnable;Ljava/lang/String;)V")]
        public Thread(global::java.lang.Object par0, global::java.lang.Runnable par1, global::java.lang.String par2) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            @__env.NewObject(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n__ctorThread46, this, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Runnable>(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Runnable;Ljava/lang/String;)V")]
        public Thread(global::java.lang.Runnable par0, global::java.lang.String par1) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.NewObject(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n__ctorThread47, this, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Runnable>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/ThreadGroup;Ljava/lang/String;)V")]
        public Thread(global::java.lang.Object par0, global::java.lang.String par1) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.NewObject(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n__ctorThread48, this, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)V")]
        public Thread(global::java.lang.String par0) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.NewObject(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n__ctorThread49, this, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/ThreadGroup;Ljava/lang/Runnable;)V")]
        public Thread(global::java.lang.Object par0, global::java.lang.Runnable par1) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.NewObject(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n__ctorThread50, this, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Runnable>(@__env, par1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/ThreadGroup;Ljava/lang/Runnable;Ljava/lang/String;J)V")]
        public Thread(global::java.lang.Object par0, global::java.lang.Runnable par1, global::java.lang.String par2, long par3) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 18)){
            @__env.NewObject(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n__ctorThread51, this, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Runnable>(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par3));
            }
        }
        
        protected Thread(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::java.lang.Thread.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int MIN_PRIORITY {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n_MIN_PRIORITY41)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int NORM_PRIORITY {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n_NORM_PRIORITY42)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int MAX_PRIORITY {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n_MAX_PRIORITY43)));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::java.lang.Thread.staticClass = @__class;
            global::java.lang.Thread.j4n_run0 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "run", "()V");
            global::java.lang.Thread.j4n_isInterrupted1 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "isInterrupted", "()Z");
            global::java.lang.Thread.j4n_currentThread2 = @__env.GetStaticMethodID(global::java.lang.Thread.staticClass, "currentThread", "()Ljava/lang/Thread;");
            global::java.lang.Thread.j4n_getName3 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "getName", "()Ljava/lang/String;");
            global::java.lang.Thread.j4n_getThreadGroup4 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "getThreadGroup", "()Ljava/lang/ThreadGroup;");
            global::java.lang.Thread.j4n_getStackTrace5 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "getStackTrace", "()[Ljava/lang/StackTraceElement;");
            global::java.lang.Thread.j4n_holdsLock6 = @__env.GetStaticMethodID(global::java.lang.Thread.staticClass, "holdsLock", "(Ljava/lang/Object;)Z");
            global::java.lang.Thread.j4n_dumpStack7 = @__env.GetStaticMethodID(global::java.lang.Thread.staticClass, "dumpStack", "()V");
            global::java.lang.Thread.j4n_setDaemon8 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "setDaemon", "(Z)V");
            global::java.lang.Thread.j4n_setPriority9 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "setPriority", "(I)V");
            global::java.lang.Thread.j4n_start10 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "start", "()V");
            global::java.lang.Thread.j4n_activeCount11 = @__env.GetStaticMethodID(global::java.lang.Thread.staticClass, "activeCount", "()I");
            global::java.lang.Thread.j4n_checkAccess12 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "checkAccess", "()V");
            global::java.lang.Thread.j4n_countStackFrames13 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "countStackFrames", "()I");
            global::java.lang.Thread.j4n_destroy14 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "destroy", "()V");
            global::java.lang.Thread.j4n_enumerate15 = @__env.GetStaticMethodID(global::java.lang.Thread.staticClass, "enumerate", "([Ljava/lang/Thread;)I");
            global::java.lang.Thread.j4n_getAllStackTraces16 = @__env.GetStaticMethodID(global::java.lang.Thread.staticClass, "getAllStackTraces", "()Ljava/util/Map;");
            global::java.lang.Thread.j4n_getContextClassLoader17 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "getContextClassLoader", "()Ljava/lang/ClassLoader;");
            global::java.lang.Thread.j4n_getDefaultUncaughtExceptionHandler18 = @__env.GetStaticMethodID(global::java.lang.Thread.staticClass, "getDefaultUncaughtExceptionHandler", "()Ljava/lang/Thread$UncaughtExceptionHandler;");
            global::java.lang.Thread.j4n_getId19 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "getId", "()J");
            global::java.lang.Thread.j4n_getPriority20 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "getPriority", "()I");
            global::java.lang.Thread.j4n_getState21 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "getState", "()Ljava/lang/Thread$State;");
            global::java.lang.Thread.j4n_getUncaughtExceptionHandler22 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "getUncaughtExceptionHandler", "()Ljava/lang/Thread$UncaughtExceptionHandler;");
            global::java.lang.Thread.j4n_interrupt23 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "interrupt", "()V");
            global::java.lang.Thread.j4n_interrupted24 = @__env.GetStaticMethodID(global::java.lang.Thread.staticClass, "interrupted", "()Z");
            global::java.lang.Thread.j4n_isAlive25 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "isAlive", "()Z");
            global::java.lang.Thread.j4n_isDaemon26 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "isDaemon", "()Z");
            global::java.lang.Thread.j4n_join27 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "join", "(JI)V");
            global::java.lang.Thread.j4n_join28 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "join", "(J)V");
            global::java.lang.Thread.j4n_join29 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "join", "()V");
            global::java.lang.Thread.j4n_resume30 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "resume", "()V");
            global::java.lang.Thread.j4n_setContextClassLoader31 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "setContextClassLoader", "(Ljava/lang/ClassLoader;)V");
            global::java.lang.Thread.j4n_setDefaultUncaughtExceptionHandler32 = @__env.GetStaticMethodID(global::java.lang.Thread.staticClass, "setDefaultUncaughtExceptionHandler", "(Ljava/lang/Thread$UncaughtExceptionHandler;)V");
            global::java.lang.Thread.j4n_setName33 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "setName", "(Ljava/lang/String;)V");
            global::java.lang.Thread.j4n_setUncaughtExceptionHandler34 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "setUncaughtExceptionHandler", "(Ljava/lang/Thread$UncaughtExceptionHandler;)V");
            global::java.lang.Thread.j4n_sleep35 = @__env.GetStaticMethodID(global::java.lang.Thread.staticClass, "sleep", "(J)V");
            global::java.lang.Thread.j4n_sleep36 = @__env.GetStaticMethodID(global::java.lang.Thread.staticClass, "sleep", "(JI)V");
            global::java.lang.Thread.j4n_stop37 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "stop", "(Ljava/lang/Throwable;)V");
            global::java.lang.Thread.j4n_stop38 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "stop", "()V");
            global::java.lang.Thread.j4n_suspend39 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "suspend", "()V");
            global::java.lang.Thread.j4n_yield40 = @__env.GetStaticMethodID(global::java.lang.Thread.staticClass, "yield", "()V");
            global::java.lang.Thread.j4n_MIN_PRIORITY41 = @__env.GetStaticFieldID(global::java.lang.Thread.staticClass, "MIN_PRIORITY", "I");
            global::java.lang.Thread.j4n_NORM_PRIORITY42 = @__env.GetStaticFieldID(global::java.lang.Thread.staticClass, "NORM_PRIORITY", "I");
            global::java.lang.Thread.j4n_MAX_PRIORITY43 = @__env.GetStaticFieldID(global::java.lang.Thread.staticClass, "MAX_PRIORITY", "I");
            global::java.lang.Thread.j4n__ctorThread44 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "<init>", "(Ljava/lang/Runnable;)V");
            global::java.lang.Thread.j4n__ctorThread45 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "<init>", "()V");
            global::java.lang.Thread.j4n__ctorThread46 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "<init>", "(Ljava/lang/ThreadGroup;Ljava/lang/Runnable;Ljava/lang/String;)V");
            global::java.lang.Thread.j4n__ctorThread47 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "<init>", "(Ljava/lang/Runnable;Ljava/lang/String;)V");
            global::java.lang.Thread.j4n__ctorThread48 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "<init>", "(Ljava/lang/ThreadGroup;Ljava/lang/String;)V");
            global::java.lang.Thread.j4n__ctorThread49 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "<init>", "(Ljava/lang/String;)V");
            global::java.lang.Thread.j4n__ctorThread50 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "<init>", "(Ljava/lang/ThreadGroup;Ljava/lang/Runnable;)V");
            global::java.lang.Thread.j4n__ctorThread51 = @__env.GetMethodID(global::java.lang.Thread.staticClass, "<init>", "(Ljava/lang/ThreadGroup;Ljava/lang/Runnable;Ljava/lang/String;J)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void run() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_run0);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public virtual bool isInterrupted() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::java.lang.Thread.j4n_isInterrupted1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/Thread;")]
        public static global::java.lang.Thread currentThread() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Thread>(@__env, @__env.CallStaticObjectMethodPtr(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n_currentThread2));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public global::java.lang.String getName() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::java.lang.Thread.j4n_getName3));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/ThreadGroup;")]
        public global::java.lang.Object getThreadGroup() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::java.lang.Thread.j4n_getThreadGroup4));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()[Ljava/lang/StackTraceElement;")]
        public virtual global::java.lang.StackTraceElement[] getStackTrace() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2Cp<global::java.lang.StackTraceElement[], global::java.lang.StackTraceElement>(@__env, @__env.CallObjectMethodPtr(this, global::java.lang.Thread.j4n_getStackTrace5));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Object;)Z")]
        public static bool holdsLock(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((bool)(@__env.CallStaticBooleanMethod(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n_holdsLock6, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public static void dumpStack() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallStaticVoidMethod(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n_dumpStack7);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Z)V")]
        public void setDaemon(bool par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_setDaemon8, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)V")]
        public void setPriority(int par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_setPriority9, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void start() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_start10);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        public static int activeCount() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallStaticIntMethod(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n_activeCount11)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public void checkAccess() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_checkAccess12);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        public virtual int countStackFrames() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::java.lang.Thread.j4n_countStackFrames13)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void destroy() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_destroy14);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("([Ljava/lang/Thread;)I")]
        public static int enumerate(global::java.lang.Thread[] par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((int)(@__env.CallStaticIntMethod(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n_enumerate15, global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par0))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/util/Map;")]
        public static global::java.util.Map getAllStackTraces() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.Map>(@__env, @__env.CallStaticObjectMethodPtr(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n_getAllStackTraces16));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/ClassLoader;")]
        public virtual global::java.lang.ClassLoader getContextClassLoader() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.ClassLoader>(@__env, @__env.CallObjectMethodPtr(this, global::java.lang.Thread.j4n_getContextClassLoader17));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/Thread$UncaughtExceptionHandler;")]
        public static global::java.lang.Object getDefaultUncaughtExceptionHandler() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallStaticObjectMethodPtr(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n_getDefaultUncaughtExceptionHandler18));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        public virtual long getId() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::java.lang.Thread.j4n_getId19)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        public int getPriority() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::java.lang.Thread.j4n_getPriority20)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/Thread$State;")]
        public virtual global::java.lang.Object getState() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::java.lang.Thread.j4n_getState21));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/Thread$UncaughtExceptionHandler;")]
        public virtual global::java.lang.Object getUncaughtExceptionHandler() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::java.lang.Thread.j4n_getUncaughtExceptionHandler22));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void interrupt() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_interrupt23);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public static bool interrupted() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallStaticBooleanMethod(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n_interrupted24)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public bool isAlive() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::java.lang.Thread.j4n_isAlive25)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public bool isDaemon() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::java.lang.Thread.j4n_isDaemon26)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(JI)V")]
        public void join(long par0, int par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_join27, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(J)V")]
        public void join(long par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_join28, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public void join() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_join29);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public void resume() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_resume30);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/ClassLoader;)V")]
        public virtual void setContextClassLoader(global::java.lang.ClassLoader par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_setContextClassLoader31, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Thread$UncaughtExceptionHandler;)V")]
        public static void setDefaultUncaughtExceptionHandler(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallStaticVoidMethod(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n_setDefaultUncaughtExceptionHandler32, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)V")]
        public void setName(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_setName33, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Thread$UncaughtExceptionHandler;)V")]
        public virtual void setUncaughtExceptionHandler(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_setUncaughtExceptionHandler34, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(J)V")]
        public static void sleep(long par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallStaticVoidMethod(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n_sleep35, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(JI)V")]
        public static void sleep(long par0, int par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.CallStaticVoidMethod(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n_sleep36, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Throwable;)V")]
        public void stop(global::java.lang.Throwable par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_stop37, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Throwable>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public void stop() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_stop38);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public void suspend() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::java.lang.Thread.j4n_suspend39);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public static void yield() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallStaticVoidMethod(global::java.lang.Thread.staticClass, global::java.lang.Thread.j4n_yield40);
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::java.lang.Thread(@__env);
            }
        }
    }
    #endregion
}
