// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system.drawing;

@net.sf.jni4net.attributes.ClrType
public class Point extends system.ValueType {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Point(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(II)V")
    public Point(int x, int y) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        system.drawing.Point.__ctorPoint0(this, x, y);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/Drawing/Size;)V")
    public Point(system.drawing.Size sz) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        system.drawing.Point.__ctorPoint1(this, sz);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(I)V")
    public Point(int dw) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        system.drawing.Point.__ctorPoint2(this, dw);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(II)V")
    private native static void __ctorPoint0(net.sf.jni4net.inj.IClrProxy thiz, int x, int y);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lsystem/drawing/Size;)V")
    private native static void __ctorPoint1(net.sf.jni4net.inj.IClrProxy thiz, system.drawing.Size sz);
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    private native static void __ctorPoint2(net.sf.jni4net.inj.IClrProxy thiz, int dw);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isEmpty();
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getX();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setX(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getY();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setY(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Point;LSystem/Drawing/Size;)LSystem/Drawing/Point;")
    public native static system.drawing.Point Add(system.drawing.Point pt, system.drawing.Size sz);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Point;LSystem/Drawing/Size;)LSystem/Drawing/Point;")
    public native static system.drawing.Point Subtract(system.drawing.Point pt, system.drawing.Size sz);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/PointF;)LSystem/Drawing/Point;")
    public native static system.drawing.Point Ceiling(system.ValueType value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/PointF;)LSystem/Drawing/Point;")
    public native static system.drawing.Point Truncate(system.ValueType value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/PointF;)LSystem/Drawing/Point;")
    public native static system.drawing.Point Round(system.ValueType value);
    
    @net.sf.jni4net.attributes.ClrMethod("(II)V")
    public native void Offset(int dx, int dy);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Point;)V")
    public native void Offset(system.drawing.Point p);
    
    public static system.Type typeof() {
        return system.drawing.Point.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        system.drawing.Point.staticType = staticType;
    }
    //</generated-proxy>
}
