// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system.drawing;

@net.sf.jni4net.attributes.ClrType
public class Size extends system.ValueType {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Size(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/Drawing/Point;)V")
    public Size(system.drawing.Point pt) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        system.drawing.Size.__ctorSize0(this, pt);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(II)V")
    public Size(int width, int height) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        system.drawing.Size.__ctorSize1(this, width, height);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Lsystem/drawing/Point;)V")
    private native static void __ctorSize0(net.sf.jni4net.inj.IClrProxy thiz, system.drawing.Point pt);
    
    @net.sf.jni4net.attributes.ClrMethod("(II)V")
    private native static void __ctorSize1(net.sf.jni4net.inj.IClrProxy thiz, int width, int height);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isEmpty();
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getWidth();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setWidth(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getHeight();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setHeight(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Size;LSystem/Drawing/Size;)LSystem/Drawing/Size;")
    public native static system.drawing.Size Add(system.drawing.Size sz1, system.drawing.Size sz2);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/SizeF;)LSystem/Drawing/Size;")
    public native static system.drawing.Size Ceiling(system.drawing.SizeF value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/Size;LSystem/Drawing/Size;)LSystem/Drawing/Size;")
    public native static system.drawing.Size Subtract(system.drawing.Size sz1, system.drawing.Size sz2);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/SizeF;)LSystem/Drawing/Size;")
    public native static system.drawing.Size Truncate(system.drawing.SizeF value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Drawing/SizeF;)LSystem/Drawing/Size;")
    public native static system.drawing.Size Round(system.drawing.SizeF value);
    
    public static system.Type typeof() {
        return system.drawing.Size.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        system.drawing.Size.staticType = staticType;
    }
    //</generated-proxy>
}
