//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace democalc {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface ICalc {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)I")]
        int MySuperSmartFunctionIDontHaveInJava(global::java.lang.String par0);
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class ICalc_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::democalc.@__ICalc.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::democalc.ICalc), typeof(global::democalc.ICalc_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::democalc.ICalc), typeof(global::democalc.ICalc_))]
    internal sealed partial class @__ICalc : global::java.lang.Object, global::democalc.ICalc {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_MySuperSmartFunctionIDontHaveInJava0;
        
        private @__ICalc(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::democalc.@__ICalc.staticClass = @__class;
            global::democalc.@__ICalc.j4n_MySuperSmartFunctionIDontHaveInJava0 = @__env.GetMethodID(global::democalc.@__ICalc.staticClass, "MySuperSmartFunctionIDontHaveInJava", "(Ljava/lang/String;)I");
        }
        
        public int MySuperSmartFunctionIDontHaveInJava(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((int)(@__env.CallIntMethod(this, global::democalc.@__ICalc.j4n_MySuperSmartFunctionIDontHaveInJava0, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0))));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__ICalc);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "MySuperSmartFunctionIDontHaveInJava", "MySuperSmartFunctionIDontHaveInJava0", "(Ljava/lang/String;)I"));
            return methods;
        }
        
        private static int MySuperSmartFunctionIDontHaveInJava0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljava/lang/String;)I
            // (Ljava/lang/String;)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::democalc.ICalc @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::democalc.ICalc>(@__env, @__obj);
            @__return = ((int)(@__real.MySuperSmartFunctionIDontHaveInJava(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::democalc.@__ICalc(@__env);
            }
        }
    }
    #endregion
}
