//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCSharpDemoCalc {
    
    
    #region Component Designer generated code 
    public partial class DemoCalc_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::MyCSharpDemoCalc.@__DemoCalc.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::MyCSharpDemoCalc.DemoCalc), typeof(global::MyCSharpDemoCalc.DemoCalc_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::MyCSharpDemoCalc.DemoCalc), typeof(global::MyCSharpDemoCalc.DemoCalc_))]
    internal sealed partial class @__DemoCalc : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__DemoCalc(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::MyCSharpDemoCalc.@__DemoCalc.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__DemoCalc);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "MySuperSmartFunctionIDontHaveInJava", "MySuperSmartFunctionIDontHaveInJava0", "(Ljava/lang/String;)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorDemoCalc0", "__ctorDemoCalc0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static int MySuperSmartFunctionIDontHaveInJava0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle question) {
            // (Ljava/lang/String;)I
            // (LSystem/String;)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::MyCSharpDemoCalc.DemoCalc @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MyCSharpDemoCalc.DemoCalc>(@__env, @__obj);
            @__return = ((int)(((global::MyCSharpDemoCalc.ICalc)(@__real)).MySuperSmartFunctionIDontHaveInJava(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, question))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void @__ctorDemoCalc0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::MyCSharpDemoCalc.DemoCalc @__real = new global::MyCSharpDemoCalc.DemoCalc();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::MyCSharpDemoCalc.@__DemoCalc(@__env);
            }
        }
    }
    #endregion
}
