// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package j4n;

@net.sf.jni4net.attributes.ClrType
public class B extends system.Object implements j4n.IB {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected B(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public B() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        j4n.B.__ctorB0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorB0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lj4n/IA;)V")
    public native void m2(j4n.IA par0);
    
    public static system.Type typeof() {
        return j4n.B.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        j4n.B.staticType = staticType;
    }
    //</generated-proxy>
}
