//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace j4n {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface IB {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lj4n/IA;)V")]
        void m2(global::j4n.IA par0);
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class IB_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::j4n.@__IB.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::j4n.IB), typeof(global::j4n.IB_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::j4n.IB), typeof(global::j4n.IB_))]
    internal sealed partial class @__IB : global::java.lang.Object, global::j4n.IB {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_m20;
        
        private @__IB(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::j4n.@__IB.staticClass = @__class;
            global::j4n.@__IB.j4n_m20 = @__env.GetMethodID(global::j4n.@__IB.staticClass, "m2", "(Lj4n/IA;)V");
        }
        
        public void m2(global::j4n.IA par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::j4n.@__IB.j4n_m20, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::j4n.IA>(@__env, par0));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__IB);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "m2", "m20", "(Lj4n/IA;)V"));
            return methods;
        }
        
        private static void m20(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Lj4n/IA;)V
            // (Lj4n/IA;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::j4n.IB @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::j4n.IB>(@__env, @__obj);
            @__real.m2(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::j4n.IA>(@__env, par0));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::j4n.@__IB(@__env);
            }
        }
    }
    #endregion
}
