// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package j4n;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class IB_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return j4n.IB_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        j4n.IB_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __IB extends system.Object implements j4n.IB {
    
    protected __IB(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Lj4n/IA;)V")
    public native void m2(j4n.IA par0);
}
//</generated-proxy>
