// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package mycsharpdemocalc;

@net.sf.jni4net.attributes.ClrType
public class DemoCalc extends system.Object implements mycsharpdemocalc.ICalc {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected DemoCalc(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public DemoCalc() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        mycsharpdemocalc.DemoCalc.__ctorDemoCalc0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorDemoCalc0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)I")
    public native int MySuperSmartFunctionIDontHaveInJava(java.lang.String question);
    
    public static system.Type typeof() {
        return mycsharpdemocalc.DemoCalc.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        mycsharpdemocalc.DemoCalc.staticType = staticType;
    }
    //</generated-proxy>
}
