//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Drawing {
    
    
    #region Component Designer generated code 
    public partial class SizeF_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::System.Drawing.@__SizeF.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::System.Drawing.SizeF), typeof(global::System.Drawing.SizeF_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::System.Drawing.SizeF), typeof(global::System.Drawing.SizeF_))]
    internal sealed partial class @__SizeF : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__SizeF(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::System.Drawing.@__SizeF.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__SizeF);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "isEmpty", "IsEmpty0", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getWidth", "Width1", "()F"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setWidth", "Width2", "(F)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getHeight", "Height3", "()F"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setHeight", "Height4", "(F)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Add", "Add5", "(Lsystem/drawing/SizeF;Lsystem/drawing/SizeF;)Lsystem/drawing/SizeF;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Subtract", "Subtract6", "(Lsystem/drawing/SizeF;Lsystem/drawing/SizeF;)Lsystem/drawing/SizeF;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ToPointF", "ToPointF7", "()Lsystem/ValueType;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ToSize", "ToSize8", "()Lsystem/drawing/Size;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSizeF0", "__ctorSizeF0", "(Lnet/sf/jni4net/inj/IClrProxy;Lsystem/drawing/SizeF;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSizeF1", "__ctorSizeF1", "(Lnet/sf/jni4net/inj/IClrProxy;Lsystem/ValueType;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSizeF2", "__ctorSizeF2", "(Lnet/sf/jni4net/inj/IClrProxy;FF)V"));
            return methods;
        }
        
        private static bool IsEmpty0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.Drawing.SizeF @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.SizeF>(@__env, @__obj);
            @__return = ((bool)(@__real.IsEmpty));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static float Width1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()F
            // ()F
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            float @__return = default(float);
            try {
            global::System.Drawing.SizeF @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.SizeF>(@__env, @__obj);
            @__return = ((float)(@__real.Width));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Width2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, float value) {
            // (F)V
            // (F)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Drawing.SizeF @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.SizeF>(@__env, @__obj);
            @__real.Width = value;
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static float Height3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()F
            // ()F
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            float @__return = default(float);
            try {
            global::System.Drawing.SizeF @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.SizeF>(@__env, @__obj);
            @__return = ((float)(@__real.Height));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Height4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, float value) {
            // (F)V
            // (F)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Drawing.SizeF @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.SizeF>(@__env, @__obj);
            @__real.Height = value;
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Add5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle sz1, global::net.sf.jni4net.utils.JniLocalHandle sz2) {
            // (Lsystem/drawing/SizeF;Lsystem/drawing/SizeF;)Lsystem/drawing/SizeF;
            // (LSystem/Drawing/SizeF;LSystem/Drawing/SizeF;)LSystem/Drawing/SizeF;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Drawing.SizeF>(@__env, global::System.Drawing.SizeF.Add(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.SizeF>(@__env, sz1), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.SizeF>(@__env, sz2)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Subtract6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle sz1, global::net.sf.jni4net.utils.JniLocalHandle sz2) {
            // (Lsystem/drawing/SizeF;Lsystem/drawing/SizeF;)Lsystem/drawing/SizeF;
            // (LSystem/Drawing/SizeF;LSystem/Drawing/SizeF;)LSystem/Drawing/SizeF;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Drawing.SizeF>(@__env, global::System.Drawing.SizeF.Subtract(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.SizeF>(@__env, sz1), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.SizeF>(@__env, sz2)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ToPointF7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/ValueType;
            // ()LSystem/Drawing/PointF;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Drawing.SizeF @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.SizeF>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Drawing.PointF>(@__env, @__real.ToPointF());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ToSize8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/drawing/Size;
            // ()LSystem/Drawing/Size;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Drawing.SizeF @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.SizeF>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Drawing.Size>(@__env, @__real.ToSize());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void @__ctorSizeF0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle size) {
            // (Lsystem/drawing/SizeF;)V
            // (LSystem/Drawing/SizeF;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Drawing.SizeF @__real = new global::System.Drawing.SizeF(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.SizeF>(@__env, size));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSizeF1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle pt) {
            // (Lsystem/ValueType;)V
            // (LSystem/Drawing/PointF;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Drawing.SizeF @__real = new global::System.Drawing.SizeF(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.PointF>(@__env, pt));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSizeF2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, float width, float height) {
            // (FF)V
            // (FF)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Drawing.SizeF @__real = new global::System.Drawing.SizeF(width, height);
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::System.Drawing.@__SizeF(@__env);
            }
        }
    }
    #endregion
}
