//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Drawing {
    
    
    #region Component Designer generated code 
    public partial class Size_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::System.Drawing.@__Size.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::System.Drawing.Size), typeof(global::System.Drawing.Size_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::System.Drawing.Size), typeof(global::System.Drawing.Size_))]
    internal sealed partial class @__Size : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__Size(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::System.Drawing.@__Size.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__Size);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "isEmpty", "IsEmpty0", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getWidth", "Width1", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setWidth", "Width2", "(I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getHeight", "Height3", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setHeight", "Height4", "(I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Add", "Add5", "(Lsystem/drawing/Size;Lsystem/drawing/Size;)Lsystem/drawing/Size;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Ceiling", "Ceiling6", "(Lsystem/drawing/SizeF;)Lsystem/drawing/Size;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Subtract", "Subtract7", "(Lsystem/drawing/Size;Lsystem/drawing/Size;)Lsystem/drawing/Size;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Truncate", "Truncate8", "(Lsystem/drawing/SizeF;)Lsystem/drawing/Size;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Round", "Round9", "(Lsystem/drawing/SizeF;)Lsystem/drawing/Size;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSize0", "__ctorSize0", "(Lnet/sf/jni4net/inj/IClrProxy;Lsystem/drawing/Point;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSize1", "__ctorSize1", "(Lnet/sf/jni4net/inj/IClrProxy;II)V"));
            return methods;
        }
        
        private static bool IsEmpty0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.Drawing.Size @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.Size>(@__env, @__obj);
            @__return = ((bool)(@__real.IsEmpty));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int Width1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Drawing.Size @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.Size>(@__env, @__obj);
            @__return = ((int)(@__real.Width));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Width2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int value) {
            // (I)V
            // (I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Drawing.Size @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.Size>(@__env, @__obj);
            @__real.Width = value;
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static int Height3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Drawing.Size @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.Size>(@__env, @__obj);
            @__return = ((int)(@__real.Height));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Height4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int value) {
            // (I)V
            // (I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Drawing.Size @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.Size>(@__env, @__obj);
            @__real.Height = value;
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Add5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle sz1, global::net.sf.jni4net.utils.JniLocalHandle sz2) {
            // (Lsystem/drawing/Size;Lsystem/drawing/Size;)Lsystem/drawing/Size;
            // (LSystem/Drawing/Size;LSystem/Drawing/Size;)LSystem/Drawing/Size;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Drawing.Size>(@__env, global::System.Drawing.Size.Add(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.Size>(@__env, sz1), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.Size>(@__env, sz2)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Ceiling6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/drawing/SizeF;)Lsystem/drawing/Size;
            // (LSystem/Drawing/SizeF;)LSystem/Drawing/Size;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Drawing.Size>(@__env, global::System.Drawing.Size.Ceiling(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.SizeF>(@__env, value)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Subtract7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle sz1, global::net.sf.jni4net.utils.JniLocalHandle sz2) {
            // (Lsystem/drawing/Size;Lsystem/drawing/Size;)Lsystem/drawing/Size;
            // (LSystem/Drawing/Size;LSystem/Drawing/Size;)LSystem/Drawing/Size;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Drawing.Size>(@__env, global::System.Drawing.Size.Subtract(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.Size>(@__env, sz1), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.Size>(@__env, sz2)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Truncate8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/drawing/SizeF;)Lsystem/drawing/Size;
            // (LSystem/Drawing/SizeF;)LSystem/Drawing/Size;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Drawing.Size>(@__env, global::System.Drawing.Size.Truncate(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.SizeF>(@__env, value)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Round9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/drawing/SizeF;)Lsystem/drawing/Size;
            // (LSystem/Drawing/SizeF;)LSystem/Drawing/Size;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Drawing.Size>(@__env, global::System.Drawing.Size.Round(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.SizeF>(@__env, value)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void @__ctorSize0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle pt) {
            // (Lsystem/drawing/Point;)V
            // (LSystem/Drawing/Point;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Drawing.Size @__real = new global::System.Drawing.Size(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Drawing.Point>(@__env, pt));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSize1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int width, int height) {
            // (II)V
            // (II)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Drawing.Size @__real = new global::System.Drawing.Size(width, height);
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::System.Drawing.@__Size(@__env);
            }
        }
    }
    #endregion
}
